import './styles/globals.css';
import ReactQueryProvider from '../../components/ReactQueryProvider';
import {ThemeProvider} from "../../components/ThemeProvider";
import { CartProvider } from '../../lib/cart';

export const metadata = {
  title: 'Amraj App',
  description: 'Generated by Next.js',
};

export default function RootLayout({ children }: { children: React.ReactNode }) {
  return (
    <html lang="en">
    <body>
    <ThemeProvider>
      <ReactQueryProvider>
        <CartProvider>
        {children}
        </CartProvider>
      </ReactQueryProvider>
      </ThemeProvider>
    </body>
  </html>
  );
}
